language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libconfuse-dev

before_script: ./autogen.sh

script: ./configure --enable-server && make check
